services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    deploy:
      replicas: 1

  front:
    image: lab1-front:latest
    ports:
      - "15000:5000"
    deploy:
      replicas: 1
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis